### ISSUE TITLE
How to restore?

### ISSUE THREAD

**Issue by pascalandy** [fukawi2/pgsql-backup#6]
What is the best practices to restaure the backup?

The exact command. I saw many ways to backup and restaure and I can't find a definitive answer yet.

Thanks!
Pascal

**Comment by fukawi2** [comment]
The default backup format is 'custom' which "is the most flexible format in that it allows reordering of loading data as well as object definitions" according to the `pg_dump` man page.

To restore an entire database ("mydb") that was dumped to "/var/backup/mydb.dump", the command is something like:

    pg_restore --create /var/backup/mydb.dump

To restore it to a different database, first create the database you want to restore it to (eg, "mydb_restore") then:

    pg_restore --dbname mydb_restore /var/backup/mydb.dump

Check the `pg_restore` man page for full options.

If you change the backup format to 'plain' then the backup file contains plain text SQL queries which you can execute with `psql` (or other client of your choice) -- you can edit the file before restoring too if you want to add/remove anything prior to restore.

**Comment by pascalandy** [comment]
Thanks you very much !!
