### ISSUE TITLE
Rolling release vs new release version

### ISSUE THREAD

**Issue by ferfebles** [fukawi2/pgsql-backup#7]
The last release is from 2014. It even predates the change "fix typo in variable preventing weekly backups being created".

Should people just install the last commited code (like a rolling release)? Or perhaps a new release should be made?

**Comment by fukawi2** [comment]
Somehow I never saw this issue until now. I'm so sorry :(

Honestly it's been that long, I'm not sure I remember how to make a release, so if you want to use it I'd suggest just cloning the head of the master branch.
